// Recorder-facing task catalog generated from task-launcher-netlify/app.js.
// Participant-facing identity is the stable list position (Task 01-31).
globalThis.GAZEAWARE_TASK_CATALOG_VERSION = "task-launcher-netlify-2026-08-18-r2";
globalThis.GAZEAWARE_TASKS = [
  ["Wikipedia", "Plant cell membrane", "Find the specific membrane in a plant cell that contains the proteins responsible for photosynthesis.", "https://en.wikipedia.org/wiki/Plant_cell"],
  ["Wikipedia", "Ancient Olympic training", "Find what kinds of preparation and training athletes underwent for the ancient Olympic Games.", "https://en.wikipedia.org/wiki/Ancient_Olympic_Games"],
  ["Gardeners", "Fertilize a garden", "Find guidance on how to fertilize a garden.", "https://www.gardeners.com/"],
  ["Sip and Feast", "Shrimp pasta recipe", "Find a pasta recipe that includes shrimp.", "https://www.sipandfeast.com/"],
  ["CHI 2026", "Workshop proposal page limit", "Find the maximum number of pages allowed for a CHI 2026 workshop proposal.", "https://chi2026.acm.org/"],
  ["BBC News", "Latest news on India", "Find the latest news about India.", "https://www.bbc.com/news"],
  ["H-E-B", "Premium chocolate ice cream", "Find the most expensive one-pint chocolate ice cream available for curbside pickup.", "https://www.heb.com/"],
  ["H-E-B", "Brownie mix under $4", "Find a brownie mix that is at least 18 oz and costs less than $4.", "https://www.heb.com/"],
  ["Amazon", "Highly rated board game", "Find a board game with at least 30,000 ratings and a rating of 4.5 stars or higher.", "https://www.amazon.com/"],
  ["Amazon", "Gift for a colleague", "Find a birthday gift for a 30-year-old colleague who enjoys cooking, with a budget of around $50.", "https://www.amazon.com/"],
  ["Reddit r/4kTV", "OLED TV reviews", "Find reviews of OLED TVs that are 50 inches or smaller.", "https://www.reddit.com/r/4kTV/"],
  ["Reddit", "Cafes near the University of Utah", "Find cafes near the University of Utah.", "https://www.reddit.com/"],
  ["CHI 2026", "Choose a workshop for an eye-tracking UI-agent paper", "Decide which CHI 2026 workshop would be the best fit for a paper on eye tracking and UI agents.", "https://chi2026.acm.org/"],
  ["CHI 2026", "Information for a first-time CHI attendee", "Explore the CHI 2026 website and identify information that would be especially useful to a first-time CHI attendee.", "https://chi2026.acm.org/"],
  ["Booking.com", "Cheapest accommodation in Seoul", "Find the cheapest available accommodation for next weekend.", "https://www.booking.com/"],
  ["Reddit r/technology", "Today’s top technology post", "Open r/technology. Select Top and Today, open the first post, and read its comments.", "https://www.reddit.com/r/technology/"],
  ["Reddit", "Accessibility app discussion", "Find a recent, popular discussion about accessibility apps and read its comments.", "https://www.reddit.com/"],
  ["YouTube", "Most replayed part of the latest MKBHD video", "Find the latest MKBHD video and navigate to its most replayed part. Use the video player’s most-replayed graph. Leave the video at its most replayed point.", "https://www.youtube.com/"],
  ["YouTube", "Shortest spaghetti cooking tutorial", "Search for a spaghetti cooking tutorial, find the shortest video in the results, and play it. Leave the video playing.", "https://www.youtube.com/"],
  ["Target", "Best-rated scented candle over $10", "Find a scented candle costing more than $10 with the highest rating.", "https://www.target.com/"],
  ["CHI 2026", "Choose a subcommittee for a scanpath paper", "Determine which CHI 2026 subcommittee would be the best fit for a paper on scanpath prediction, then leave the relevant subcommittee page open.", "https://chi2026.acm.org/"],
  ["Apple", "Apple Intelligence tools", "On the MacBook Air pages, find information about the tools that Apple Intelligence is built into, then leave the relevant page open.", "https://www.apple.com/macbook-air/"],
  ["Expedia", "Flight from Salt Lake City for UIST 2026", "Find a suitable economy itinerary for the first in-person UIST 2026 event in Detroit.", "https://www.expedia.com/Flights"],
  ["University of Utah", "Choose a potential faculty advisor", "You plan to apply to the Computer Science PhD program. Find at least two faculty members whose work matches your interests in HCI, accessible computing, and computer vision. Check whether they state that they are recruiting Fall 2027 students, choose the one you would most want to contact, and leave their faculty page open.", "https://www.cs.utah.edu/graduate/prospective-students/admissions/research-areas/"],
  ["University of Utah", "Compare MS and PhD funding", "Starting from the Kahlert School of Computing homepage, compare the financial support available to MS and PhD students. Check RA, TA, and assistantship options, tuition benefits, and whether support is guaranteed for new students, then leave the most relevant source page open.", "https://www.cs.utah.edu/"],
  ["Amazon", "Products for a new home office", "Browse Amazon and choose five products that would be useful for setting up a new home office.", "https://www.amazon.com/"],
  ["University of Utah", "Graduate application fee and deadlines", "Find the graduate application fee and application deadline.", "https://www.cs.utah.edu/"],
  ["Google Search", "Return to the search results", "Search for an article about how to do a literature review, open the first result, then use the browser Back button to return to the search results.", "https://www.google.com/"],
  ["CHI 2026", "Accessibility Best Papers", "Find at least two CHI 2026 Best Papers related to accessibility. Compare them, then follow an author from one paper to another paper they have authored.", "https://programs.sigchi.org/chi/2026/awards/best-papers"],
  ["YouTube", "Switch to the next lecture video", "Search YouTube for “llm from scratch,” play the first suggested video for a few seconds, then skip to the next video.", "https://www.youtube.com/"],
  ["Wikipedia", "From touch typing to University of Utah", "Starting from the Touch typing Wikipedia page, find a path to a University of Utah page and leave the destination page open.", "https://en.wikipedia.org/wiki/Touch_typing"],
].map(([site, title, prompt, url], index) => Object.freeze({
  taskId: String(index + 1).padStart(2, "0"),
  taskNumber: index + 1,
  site,
  title,
  prompt,
  url
}));
